package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"backend/graphql/generated"
	"context"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input generated.CreatePostInput) (*generated.CreatePostResult, error) {
	post, err := r.Postgres.CreatePost(ctx, input)
	if err != nil {
		return nil, err
	}
	return &generated.CreatePostResult{Post: post}, nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	return r.Postgres.DeletePost(ctx, id)
}

// Author is the resolver for the author field.
func (r *postResolver) Author(ctx context.Context, obj *generated.Post) (*generated.User, error) {
	return r.Postgres.GetUser(ctx, obj.Author.ID)
}

// GetPost is the resolver for the getPost field.
func (r *queryResolver) GetPost(ctx context.Context, input generated.GetPostInput) (*generated.GetPostResult, error) {
	post, err := r.Postgres.GetPost(ctx, input.ID)
	if err != nil {
		return nil, err
	}
	return &generated.GetPostResult{Post: post}, nil
}

// AllPosts is the resolver for the allPosts field.
func (r *queryResolver) AllPosts(ctx context.Context) ([]*generated.Post, error) {
	return r.Postgres.AllPosts(ctx)
}

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

type postResolver struct{ *Resolver }
