package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"backend/graphql/generated"
	"context"
	"strconv"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input generated.CreateUserInput) (*generated.CreateUserResult, error) {
	// You can implement this in db/postgres.go later if needed
	return nil, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, input generated.GetUserInput) (*generated.GetUserResult, error) {
	user, err := r.Postgres.GetUser(ctx, input.ID)
	if err != nil {
		return nil, err
	}
	return &generated.GetUserResult{User: user}, nil
}

// Posts is the resolver for the posts field.
func (r *userResolver) Posts(ctx context.Context, obj *generated.User) ([]*generated.Post, error) {
	query := `SELECT id, title, content, published FROM posts WHERE author_id = $1`

	// Convert ID safely
	userID, err := strconv.Atoi(obj.ID)
	if err != nil {
		return nil, err
	}

	rows, err := r.Postgres.GetPool().Query(ctx, query, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var posts []*generated.Post
	for rows.Next() {
		post := &generated.Post{}
		var tempID int

		err := rows.Scan(&tempID, &post.Title, &post.Content, &post.Published)
		if err != nil {
			return nil, err
		}

		post.ID = strconv.Itoa(tempID)
		posts = append(posts, post)
	}

	return posts, nil
}


// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
